name: yakuza
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # For making HTTP requests
  http: ^1.2.1

  # For SQLite database
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3 # To find the correct local path for the database
  path: ^1.9.0 # For path manipulation

  # For state management (simple and effective for this scale)
  provider: ^6.1.2

  # For icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
